version: '3.8'

services:
  eureka-server:
    build:
      context: ./Eureka-Server
    ports:
      - "8761:8761"
    environment:
      - JAVA_OPTS=-Xmx96m -Xms96m
    networks:
      - ecommerce-net

  api-gateway:
    build:
      context: ./Api-Gateway
    ports:
      - "8080:8080"
    environment:
      - EUREKA_URL=http://eureka-server:8761/eureka/
      - PORT=8080
      - JAVA_OPTS=-Xmx110m -Xms110m
    depends_on:
      - eureka-server
    networks:
      - ecommerce-net

  microservice-usuario:
    build:
      context: ./MicroService-Usuario
    ports:
      - "8081:8081"
    environment:
      - EUREKA_URL=http://eureka-server:8761/eureka/
      - PORT=8081
      - SPRING_DATASOURCE_URL=jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}
      - SPRING_DATASOURCE_USERNAME=${MYSQLUSER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQLPASSWORD}
      - JAVA_OPTS=-Xmx110m -Xms110m
    depends_on:
      - eureka-server
    networks:
      - ecommerce-net

networks:
  ecommerce-net:
    driver: bridge