spring:
  application:
    name: MicroService-Notificacion

  datasource:
    url: jdbc:mysql://localhost:3306/db_notificacion
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  flyway:
    enabled: true

server:
  port: 8089

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /notificacion/swagger-ui.html

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

microservicios:
  usuarios:
    url: ${USUARIOS_SERVICE_URL:http://localhost:8081}