spring:
  application:
    name: MicroService-Inventario

  datasource:
    url: jdbc:mysql://localhost:3306/db_inventario
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  flyway:
    enabled: true
    ignore-migration-patterns: "*:*"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

server:
  port: 8084

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /inventario/swagger-ui.html

microservicios:
  productos:
    url: ${PRODUCTO_URL:http://localhost:8083/v1/productos}